### ISSUE TITLE
three-ways branching, how to deal with it?

### ISSUE THREAD

**Issue by huangziwei** [berenslab/MorphoPy#99]
Normally, there will be only two branches stemming from one branchpoint. However, situations of three branches from one branchpoint exist.

It's the main reason the I removed the Strahler order (it only deals with two). Also when calculating the angles between branches, one branch of the three-ways branching is ignored (just found out...).

My question is that is three-ways branching in the data just human error made in cell tracing or really exists in neuronal morphology?

**Comment by Visdoom** [comment]
hmmm,  I think , generally, it is a matter of definition whether a neuron can branch three fold or not. However, I think we should be able to deal with that situation code wise. In terms of branching angles I would propose to calculate all possible angles. Since these situations occur rather scarcely one would not bias a distribution or average too much but one does not just throw out information either.
